### ISSUE TITLE
默认日志存储目录好像没有文件

### ISSUE THREAD

**Issue by dongyiming** [vip001/framemonitor#1]

**Comment by vip001** [comment]
当达到保存堆栈到本地文件的帧绘制时间阀值时，在logcat会输出文件保存路径：The application may be doing too much work on its main thread.The log file is written to 【filepath】 。
默认会保存在【getExternalCacheDir】／framemonitor／log中，如果sd卡保存失败会保存到手机内存中。

检查下locat有没有输出路径

**Comment by dongyiming** [comment]
> 当达到保存堆栈到本地文件的帧绘制时间阀值时，在logcat会输出文件保存路径：The application may be doing too much work on its main thread.The log file is written to 【filepath】 。
> 默认会保存在【getExternalCacheDir】／framemonitor／log中，如果sd卡保存失败会保存到手机内存中。
> 
> 检查下locat有没有输出路径

找到了，我看你的博客，没有找自己的项目目录，找的你的vip这个，是没有的，在自己的cache下 找到了，谢谢
